spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false
  messages:
    basename: "i18n/messages"
  thymeleaf:
    mode : HTML

logging:
  level:
    com:
      slgerkamp:
        psychological:
          safety:
            game: DEBUG

security:
  oauth2:
    client:
      client-authentication-scheme: header
      user-authorization-uri: https://access.line.me/oauth2/v2.1/authorize?scope=profile&bot_prompt=aggressive
      access-token-uri: https://api.line.me/oauth2/v2.1/token
    resource:
      user-info-uri: https://api.line.me/v2/profile

