spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false
  messages:
    basename: "i18n/messages"
  thymeleaf:
    mode : HTML

logging:
  level:
    com:
      slgerkamp:
        psychological:
          safety:
            game: DEBUG

